#!/bin/sh
jekyll build

# The following directories are excluded from the list
# of files to copy on the jekyll build. We use symlinks
# to them from the _site subdirectory.

# 1. Jekyll doesn't handle ok copying a directory with
# symlinks (references to the stable/unstable versions)
ln -s ../reference _site/reference
# 2. Copying many tarballs is expensive.
ln -s ../releases _site/releases
