name: build-pr

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
            npm-
      - name: Install Node modules
        run: npm install
      - name: Eleventy
        run: |
          ./node_modules/.bin/eleventy \
            --output='_site/${{ github.head_ref }}' \
            --pathprefix='/wpewebkit.org/${{ github.head_ref }}'
          LC_TIME=C date > '_site/${{ github.head_ref }}/.stamp'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
      - name: Add deploy link
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get all the comments.
            const comments = await github.paginate(github.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // If we commented already, skip.
            for (const comment of comments) {
              if (comment.user.login == 'github-actions' && comment.body.startsWith('Site preview:'))
                return;
            }

            // Otherwise, create the comment.
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Site preview: https://igalia.github.io/wpewebkit.org/${{ github.head_ref }}',
            });
